### ISSUE TITLE
Unsafe iteration over array

### ISSUE THREAD

**Issue by sasasagagaga** [RandomAtHome/parallel_block_sort#1]
Here in line 73 you can face an overflow in the case of buffer of size 0. https://github.com/RandomAtHome/parallel_block_sort/blob/2fa7f11fdee995c0cf4469d37021da9b34921251/main.c#L71-L79
You should be careful when decrementing the values of unsigned variables.

**Comment by RandomAtHome** [comment]
Thank you for the heads-up!
I wonder why pre-decrement was used here, whereas in other places post-decrement is used normally.
Better fix late than never :)
